from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

class Ui_Home(object):
    def setupUi(self, Form):
        Form.setWindowIcon(QIcon('img/icon.png'))
        Form.setObjectName("Form")
        Form.resize(1145, 650)
        Form.setMinimumSize(QtCore.QSize(1145, 650))
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(143, 136, 117, 255), stop:0.5 rgba(124, 95, 78, 255), stop:1 rgba(101, 54, 56, 255));")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(25, 25, 25, 25)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalWidget_Top = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget_Top.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_Top.setSizePolicy(sizePolicy)
        self.horizontalWidget_Top.setMaximumSize(QtCore.QSize(16777215, 31))
        self.horizontalWidget_Top.setStyleSheet("background-color: transparent;")
        self.horizontalWidget_Top.setObjectName("horizontalWidget_Top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_Top)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_2.setContentsMargins(-1, 1, 1, -1)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.buttonInfo = QtWidgets.QPushButton(self.horizontalWidget_Top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonInfo.sizePolicy().hasHeightForWidth())
        self.buttonInfo.setSizePolicy(sizePolicy)
        self.buttonInfo.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonInfo.setMaximumSize(QtCore.QSize(31, 31))
        self.buttonInfo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonInfo.setStyleSheet("#buttonInfo {background-color: transparent;background-image: url(:/home/img/home/info.svg);border: none;background-repeat: none;}#buttonInfo:hover {background-image:  url(:/home/img/home/a_info.svg)}")
        self.buttonInfo.setText("")
        self.buttonInfo.setObjectName("buttonInfo")
        self.horizontalLayout_2.addWidget(self.buttonInfo)
        self.verticalLayout.addWidget(self.horizontalWidget_Top)
        self.horizontalWidget_Button = QtWidgets.QWidget(Form)
        self.horizontalWidget_Button.setStyleSheet("background-color: transparent;")
        self.horizontalWidget_Button.setObjectName("horizontalWidget_Button")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget_Button)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 31)
        self.horizontalLayout.setSpacing(60)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonLibrary = QtWidgets.QPushButton(self.horizontalWidget_Button)
        self.buttonLibrary.setMinimumSize(QtCore.QSize(186, 216))
        self.buttonLibrary.setMaximumSize(QtCore.QSize(186, 216))
        self.buttonLibrary.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonLibrary.setStyleSheet("#buttonLibrary {background-color: transparent;background-image: url(:/home/img/home/library_icon.svg);border: none;background-repeat: none;}#buttonLibrary:hover {background-image:  url(:/home/img/home/a_library_icon.svg);}")
        self.buttonLibrary.setText("")
        self.buttonLibrary.setObjectName("buttonLibrary")
        self.horizontalLayout.addWidget(self.buttonLibrary)
        self.buttonSales = QtWidgets.QPushButton(self.horizontalWidget_Button)
        self.buttonSales.setMinimumSize(QtCore.QSize(186, 216))
        self.buttonSales.setMaximumSize(QtCore.QSize(186, 216))
        self.buttonSales.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonSales.setStyleSheet("#buttonSales {background-color: transparent;background-image: url(:/home/img/home/sales_icon.svg);border: none;background-repeat: none;}#buttonSales:hover {background-image:  url(:/home/img/home/a_sales_icon.svg);}")
        self.buttonSales.setText("")
        self.buttonSales.setObjectName("buttonSales")
        self.horizontalLayout.addWidget(self.buttonSales)
        self.buttonCustomers = QtWidgets.QPushButton(self.horizontalWidget_Button)
        self.buttonCustomers.setMinimumSize(QtCore.QSize(186, 216))
        self.buttonCustomers.setMaximumSize(QtCore.QSize(186, 216))
        self.buttonCustomers.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonCustomers.setStyleSheet("#buttonCustomers {background-color: transparent;background-image: url(:/home/img/home/customers_icon.svg);border: none;background-repeat: none;}#buttonCustomers:hover {background-image:  url(:/home/img/home/a_customers_icon.svg);}")
        self.buttonCustomers.setText("")
        self.buttonCustomers.setObjectName("buttonCustomers")
        self.horizontalLayout.addWidget(self.buttonCustomers)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.horizontalWidget_Button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Bookstore"))
import resources